version: '3.8'
services:
  backend:
    build: ./server
    hostname: api
    networks:
      - webapp
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: RedDb
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: RedTeam197
    ports:
      - '5432:5432' # Remove during prod


networks:
  webapp:
    driver: bridge