version: '3.8'
services:
  backend:
    restart: always
    build: ./server
    hostname: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - media_volume:/server/media

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: RedDb
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: RedTeam197
    ports:
      - '5432:5432' # Remove during prod

volumes:
  media_volume: